version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: resresres
      POSTGRES_USER: resresres
      POSTGRES_PASSWORD: resresres
