name:    resresres
version: "0.0.0"

dependencies: 
- aeson >=1.4 && <1.5
- base >=4.9.1.0 && <5
- bytestring >=0.10 && <0.11
- case-insensitive
- classy-prelude >=1.5 && <1.6
- classy-prelude-conduit >=1.5 && <1.6
- classy-prelude-yesod >=1.5 && <1.6
- conduit >=1.0 && <2.0
- containers
- data-default
- directory >=1.1 && <1.4
- esqueleto
- fast-logger >=2.2 && <3.1
- file-embed
- flow
- foreign-store
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- lens
- lens-aeson
- monad-control >=0.3 && <1.1
- monad-logger >=0.3 && <0.4
- persistent >=2.9 && <2.11
- persistent-postgresql >=2.9 && <2.11
- persistent-template >=2.5 && <2.9
- safe
- template-haskell
- text >=0.11 && <2.0
- time
- unordered-containers
- validation
- vector
- wai
- wai-extra >=3.0 && <3.1
- wai-logger >=2.2 && <2.4
- warp >=3.0 && <3.4
- yaml >=0.11 && <0.12
- yesod >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-form >=1.6 && <1.7

default-extensions:
- DeriveAnyClass
- DeriveGeneric
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  resresres:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - resresres
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  resresres-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - hspec >=2.0.0
    - resresres
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
